### ISSUE TITLE
Бесконечный цикл

### ISSUE THREAD

**Issue by MAARRIIK** [timagr615/dmarket_bot#2]
async def update_offers_loop():

Не проходит дальше данного цикла
Строка из Debug 
2021-09-09 01:06:56.023 | INFO     | __main__:main:104 - Запуск бота
2021-09-09 01:06:56.054 | DEBUG    | __main__:history_loop:51 - History loop
2021-09-09 01:07:02.868 | INFO     | __main__:create_pre_base:20 - Обработка базы скинов
2021-09-09 01:07:02.868 | DEBUG    | modules.skinbase:update_base:77 - Games.CS
2021-09-09 01:07:02.875 | DEBUG    | __main__:orders_loop:32 - orders loop
2021-09-09 01:07:02.876 | DEBUG    | __main__:orders_loop:34 - 0
2021-09-09 01:07:13.927 | DEBUG    | modules.offers:update_offers:128 - UPDATE OFFERS: Result=[]
2021-09-09 01:07:13.941 | DEBUG    | api.dmarketapi:get_balance:123 - BALANCE: 193
2021-09-09 01:07:14.136 | DEBUG    | __main__:orders_loop:42 - Не хватает денег для выставления ордеров, откладываем аналитику
2021-09-09 01:07:14.177 | DEBUG    | modules.offers:add_to_sell:89 - Add to sell: Result=[]
2021-09-09 01:07:31.763 | DEBUG    | modules.offers:add_to_sell:89 - Add to sell: Result=[]
2021-09-09 01:07:31.792 | DEBUG    | modules.offers:update_offers:128 - UPDATE OFFERS: Result=[]

И так бесконечно
Если смотреть по стопам дебага, то он создает базу и постоянно смотрит на инвентарь на сайте, но не переходит на выставление ордеров и анализу
Конфиг выставлен весь правильно

**Comment by MAARRIIK** [comment]
Так же никогда не переходит на данные строки, хотя прайсы никогда  не равны, но он почему то строку пропускает
                if round(price, 2) != round(i.sellPrice, 2):
                    i.sellPrice = price
                    items_to_update.append(EditOffer(OfferID=i.OfferID, AssetID=i.AssetID,
                                                     Price=LastPrice(Currency='USD', Amount=round(i.sellPrice, 2))))

**Comment by timagr615** [comment]
> async def update_offers_loop():
> 
> Не проходит дальше данного цикла
> Строка из Debug
> 2021-09-09 01:06:56.023 | INFO | **main**:main:104 - Запуск бота
> 2021-09-09 01:06:56.054 | DEBUG | **main**:history_loop:51 - History loop
> 2021-09-09 01:07:02.868 | INFO | **main**:create_pre_base:20 - Обработка базы скинов
> 2021-09-09 01:07:02.868 | DEBUG | modules.skinbase:update_base:77 - Games.CS
> 2021-09-09 01:07:02.875 | DEBUG | **main**:orders_loop:32 - orders loop
> 2021-09-09 01:07:02.876 | DEBUG | **main**:orders_loop:34 - 0
> 2021-09-09 01:07:13.927 | DEBUG | modules.offers:update_offers:128 - UPDATE OFFERS: Result=[]
> 2021-09-09 01:07:13.941 | DEBUG | api.dmarketapi:get_balance:123 - BALANCE: 193
> 2021-09-09 01:07:14.136 | DEBUG | **main**:orders_loop:42 - Не хватает денег для выставления ордеров, откладываем аналитику
> 2021-09-09 01:07:14.177 | DEBUG | modules.offers:add_to_sell:89 - Add to sell: Result=[]
> 2021-09-09 01:07:31.763 | DEBUG | modules.offers:add_to_sell:89 - Add to sell: Result=[]
> 2021-09-09 01:07:31.792 | DEBUG | modules.offers:update_offers:128 - UPDATE OFFERS: Result=[]
> 
> И так бесконечно
> Если смотреть по стопам дебага, то он создает базу и постоянно смотрит на инвентарь на сайте, но не переходит на выставление ордеров и анализу
> Конфиг выставлен весь правильно

Это просиходило из-за того, что в файле `main.py` я поставил ограничение в петле выставления ордеров на баланс. Если баланс на 10 долларов меньше, чем цена минимально возможного ордера, то они не выставляются.
В [коммите](https://github.com/timagr615/dmarket_bot/commit/f1a9a9d77559bb081dfd8848776c9aac6a565cf1) добавил параметр `STOP_ORDERS_BALANCE = 1000` - означающий остановку выставления ордеров при балансе на 10 долларов (1000 центов) меньше, чем минимальная цена ордера.

**Comment by timagr615** [comment]
> Так же никогда не переходит на данные строки, хотя прайсы никогда не равны, но он почему то строку пропускает
> if round(price, 2) != round(i.sellPrice, 2):
> i.sellPrice = price
> items_to_update.append(EditOffer(OfferID=i.OfferID, AssetID=i.AssetID,
> Price=LastPrice(Currency='USD', Amount=round(i.sellPrice, 2))))

Эту ошибку исправил в [коммите 65a7d1b64d39722111f7df957205f1b3477cb4b3](https://github.com/timagr615/dmarket_bot/commit/65a7d1b64d39722111f7df957205f1b3477cb4b3). Она возникала из-за разной длины массивов в  
`on_sell и agr` в данном месте:
``` python
        on_sell = sorted([i for i in SelectSkinOffer.select_not_sell() if i.OfferID is not None],
                         key=lambda x: x.title)
        names = [i.title for i in on_sell]
        agr = await self.bot.agregated_prices(names=names, limit=len(names))
        items_to_update = list()
        for i, j in zip(on_sell, agr):
            best_price = j.Offers.BestPrice
            if i.sellPrice != best_price:


                max_sell_price = i.buyPrice * (1 + self.max_percent / 100 + i.fee / 100)
                min_sell_price = i.buyPrice * (1 + self.min_percent / 100 + i.fee / 100)
                price = self.offer_price(max_sell_price, min_sell_price, best_price)
                if round(price, 2) != round(i.sellPrice, 2):
                    # logger.info(f'{i.sellPrice} {best_price} {price} {i.fee}')
                    i.sellPrice = price
                    items_to_update.append(EditOffer(OfferID=i.OfferID, AssetID=i.AssetID,
                                                     Price=LastPrice(Currency='USD', Amount=i.sellPrice)))
```
